on: push
name: PHPUnit
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: mattiasgeniar/php73

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
          repository: muhghazaliakbar/nova
          token: ${{ secrets.NOVA }}
      - name: Configure git
        env:
          TOKEN: e0779d86a007ea8e7ed698a489175a80850ae77b
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - name: Install composer dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache
      - name: Compile assets
        run: |
          yarn install --pure-lockfile
          yarn run production --progress false
      - name: Set custom php.ini settings
        run: echo 'short_open_tag=off' >> /usr/local/etc/php/php.ini
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate
      - name: Run Testsuite
        run: vendor/bin/phpunit tests/
